/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author JESSY
 */
public class ModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarProducto
     */
    public ModificarProducto() {
        initComponents();
        
        //Descactivas la opción de ampliar pantalla
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Nombre_ModificarProducto = new javax.swing.JTextField();
        txt_Codigo_ModificarProducto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Stock_ModificarProducto = new javax.swing.JTextField();
        cbx_Mascota_ModificarProducto = new javax.swing.JComboBox<>();
        cbx_Marca_ModificarProducto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_Modificar_ModificarProducto = new javax.swing.JButton();
        btn_Cancelar_ModificarProducto = new javax.swing.JButton();
        btn_AgregarMascota_ModificarProducto = new javax.swing.JButton();
        btn_AgregarMarca_ModificarProducto = new javax.swing.JButton();
        txt_Precio_ModificarProducto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("© 2024. Creado y diseñado por Peter Son Alcoser");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESSY\\OneDrive - Universidad Tecnologica del Peru\\ciclo 7\\integrador 1\\proyecto 1\\SupertPet\\src\\main\\java\\Imagenes\\interfaz\\ImgModificarProducto\\imagen2.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 70, 430, 570));

        jPanel1.setBackground(new java.awt.Color(75, 90, 165));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SuperPet");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESSY\\OneDrive - Universidad Tecnologica del Peru\\ciclo 7\\integrador 1\\proyecto 1\\SupertPet\\src\\main\\java\\Imagenes\\interfaz\\ImgRegistrarEmpleado\\imagen1.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 650));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel5.setText("Crear producto:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel6.setText("Nombre del producto:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel7.setText("Código:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txt_Nombre_ModificarProducto.setBackground(new java.awt.Color(197, 254, 254));
        jPanel2.add(txt_Nombre_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 350, 30));

        txt_Codigo_ModificarProducto.setBackground(new java.awt.Color(197, 254, 254));
        jPanel2.add(txt_Codigo_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 350, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel8.setText("Precio de venta:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txt_Stock_ModificarProducto.setBackground(new java.awt.Color(197, 254, 254));
        jPanel2.add(txt_Stock_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 190, 30));

        cbx_Mascota_ModificarProducto.setBackground(new java.awt.Color(197, 254, 254));
        cbx_Mascota_ModificarProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Perro/Gato" }));
        jPanel2.add(cbx_Mascota_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 230, 30));

        cbx_Marca_ModificarProducto.setBackground(new java.awt.Color(197, 254, 254));
        cbx_Marca_ModificarProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cambo", "SuperCan", "SuperCat" }));
        jPanel2.add(cbx_Marca_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 230, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel9.setText("Stock");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel11.setText("¿Para qué tipos mascotas?");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        btn_Modificar_ModificarProducto.setBackground(new java.awt.Color(207, 202, 250));
        btn_Modificar_ModificarProducto.setText("Modificar");
        btn_Modificar_ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar_ModificarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Modificar_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 100, 40));

        btn_Cancelar_ModificarProducto.setBackground(new java.awt.Color(240, 65, 116));
        btn_Cancelar_ModificarProducto.setText("Cancelar");
        btn_Cancelar_ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancelar_ModificarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cancelar_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 100, 40));

        btn_AgregarMascota_ModificarProducto.setBackground(new java.awt.Color(240, 187, 245));
        btn_AgregarMascota_ModificarProducto.setText("Agregar Mascotas");
        btn_AgregarMascota_ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarMascota_ModificarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_AgregarMascota_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 130, 30));

        btn_AgregarMarca_ModificarProducto.setBackground(new java.awt.Color(240, 187, 245));
        btn_AgregarMarca_ModificarProducto.setText("Agregar Marca");
        btn_AgregarMarca_ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarMarca_ModificarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_AgregarMarca_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 130, 30));

        txt_Precio_ModificarProducto.setBackground(new java.awt.Color(197, 254, 254));
        jPanel2.add(txt_Precio_ModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel12.setText("Marca:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 10)); // NOI18N
        jLabel13.setText("Tiene que ser mayor o igual a Cero \"0\"");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESSY\\OneDrive - Universidad Tecnologica del Peru\\ciclo 7\\integrador 1\\proyecto 1\\SupertPet\\src\\main\\java\\Imagenes\\interfaz\\ImgModificarProducto\\imagen4.png")); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabel3.setBackground(new java.awt.Color(197, 254, 254));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESSY\\OneDrive - Universidad Tecnologica del Peru\\ciclo 7\\integrador 1\\proyecto 1\\SupertPet\\src\\main\\java\\Imagenes\\interfaz\\ImgModificarProducto\\imagen3.png")); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 680, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Cancelar_ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancelar_ModificarProductoActionPerformed
        GestionarAlmacen ga = new GestionarAlmacen();
        ga.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Cancelar_ModificarProductoActionPerformed

    private void btn_AgregarMarca_ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarMarca_ModificarProductoActionPerformed
        AgregarMarca2 am2 = new AgregarMarca2();
        am2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_AgregarMarca_ModificarProductoActionPerformed

    private void btn_AgregarMascota_ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarMascota_ModificarProductoActionPerformed
        AgregarMascota2 am2 = new AgregarMascota2();
        am2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_AgregarMascota_ModificarProductoActionPerformed

    private void btn_Modificar_ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar_ModificarProductoActionPerformed
        GestionarAlmacen ga = new GestionarAlmacen();
        ga.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Modificar_ModificarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AgregarMarca_ModificarProducto;
    private javax.swing.JButton btn_AgregarMascota_ModificarProducto;
    private javax.swing.JButton btn_Cancelar_ModificarProducto;
    private javax.swing.JButton btn_Modificar_ModificarProducto;
    private javax.swing.JComboBox<String> cbx_Marca_ModificarProducto;
    private javax.swing.JComboBox<String> cbx_Mascota_ModificarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_Codigo_ModificarProducto;
    private javax.swing.JTextField txt_Nombre_ModificarProducto;
    private javax.swing.JTextField txt_Precio_ModificarProducto;
    private javax.swing.JTextField txt_Stock_ModificarProducto;
    // End of variables declaration//GEN-END:variables
}
