/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author JESSY
 */
public class RegistrarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarEmpleado
     */
    public RegistrarEmpleado() {
        initComponents();
        
        //Descactivas la opción de ampliar pantalla
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ck_Activo_DatoEmpleado = new javax.swing.JCheckBox();
        ck_Inactivo_DatoEmpleado = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cbx_PuestoTrabajo_DatoEmpleado = new javax.swing.JComboBox<>();
        btn_CrearPuesto_DatoEmpleado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_Apellido_DatoEmpleado = new javax.swing.JTextField();
        txt_DNI_DatoEmpleado = new javax.swing.JTextField();
        txt_NumeroContacto_DatoEmpleado = new javax.swing.JTextField();
        txt_Nombre_DatoEmpleado = new javax.swing.JTextField();
        cbx_Sexo_DatoEmpleado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_Registrar_DatoEmpleado = new javax.swing.JButton();
        btn_Cancelar_DatoEmpleado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 241, 216));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESSY\\OneDrive - Universidad Tecnologica del Peru\\ciclo 7\\integrador 1\\proyecto 1\\SupertPet\\src\\main\\java\\Imagenes\\interfaz\\ImgRegistrarEmpleado\\imagen1.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Broadway", 0, 24)); // NOI18N
        jLabel4.setText("SuperPet");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 140, 30));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel2.setText("Puesto de trabajo del empleado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        ck_Activo_DatoEmpleado.setBackground(new java.awt.Color(248, 241, 216));
        ck_Activo_DatoEmpleado.setText("Activo");
        ck_Activo_DatoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck_Activo_DatoEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(ck_Activo_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        ck_Inactivo_DatoEmpleado.setBackground(new java.awt.Color(248, 241, 216));
        ck_Inactivo_DatoEmpleado.setText("Inactivo");
        jPanel1.add(ck_Inactivo_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESSY\\OneDrive - Universidad Tecnologica del Peru\\ciclo 7\\integrador 1\\proyecto 1\\SupertPet\\src\\main\\java\\Imagenes\\interfaz\\ImgRegistrarEmpleado\\imagen2.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cbx_PuestoTrabajo_DatoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rellenador", "Cajero", "Gestión de almacén" }));
        jPanel1.add(cbx_PuestoTrabajo_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 30));

        btn_CrearPuesto_DatoEmpleado.setBackground(new java.awt.Color(250, 187, 92));
        btn_CrearPuesto_DatoEmpleado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CrearPuesto_DatoEmpleado.setText("Crear puesto laboral");
        btn_CrearPuesto_DatoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearPuesto_DatoEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CrearPuesto_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, -1));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel6.setText("Estado del Empleado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESSY\\OneDrive - Universidad Tecnologica del Peru\\ciclo 7\\integrador 1\\proyecto 1\\SupertPet\\src\\main\\java\\Imagenes\\interfaz\\ImgRegistrarEmpleado\\imagen3.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("© 2024. Creado y diseñado por Peter Son Alcoser");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 640));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setText("Datos del empleado:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txt_Apellido_DatoEmpleado.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jPanel2.add(txt_Apellido_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, 30));

        txt_DNI_DatoEmpleado.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        txt_DNI_DatoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DNI_DatoEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_DNI_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 280, 30));

        txt_NumeroContacto_DatoEmpleado.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jPanel2.add(txt_NumeroContacto_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 280, 30));

        txt_Nombre_DatoEmpleado.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        txt_Nombre_DatoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre_DatoEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Nombre_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 280, 30));

        cbx_Sexo_DatoEmpleado.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        cbx_Sexo_DatoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        jPanel2.add(cbx_Sexo_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 150, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel9.setText("Nombres:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel10.setText("Apellidos:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel11.setText("DNI:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel12.setText("Sexo:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        jLabel13.setText("Número de contacto:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        btn_Registrar_DatoEmpleado.setBackground(new java.awt.Color(250, 187, 92));
        btn_Registrar_DatoEmpleado.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        btn_Registrar_DatoEmpleado.setText("Registrar");
        btn_Registrar_DatoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Registrar_DatoEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Registrar_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 240, 30));

        btn_Cancelar_DatoEmpleado.setBackground(new java.awt.Color(16, 60, 173));
        btn_Cancelar_DatoEmpleado.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        btn_Cancelar_DatoEmpleado.setText("Cancelar");
        btn_Cancelar_DatoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancelar_DatoEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Cancelar_DatoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 580, 100, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESSY\\OneDrive - Universidad Tecnologica del Peru\\ciclo 7\\integrador 1\\proyecto 1\\SupertPet\\src\\main\\java\\Imagenes\\interfaz\\ImgRegistrarEmpleado\\imagen4.png")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 600));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 550, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ck_Activo_DatoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck_Activo_DatoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ck_Activo_DatoEmpleadoActionPerformed

    private void txt_Nombre_DatoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre_DatoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre_DatoEmpleadoActionPerformed

    private void txt_DNI_DatoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DNI_DatoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DNI_DatoEmpleadoActionPerformed

    private void btn_Cancelar_DatoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancelar_DatoEmpleadoActionPerformed
        GestionarEmpleado ge = new GestionarEmpleado();
        ge.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Cancelar_DatoEmpleadoActionPerformed

    private void btn_Registrar_DatoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Registrar_DatoEmpleadoActionPerformed
        
        CodigoAutogenerado cag = new CodigoAutogenerado();
        cag.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_Registrar_DatoEmpleadoActionPerformed

    private void btn_CrearPuesto_DatoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearPuesto_DatoEmpleadoActionPerformed
        CrearPuestoTrabajo cpt = new CrearPuestoTrabajo();
        cpt.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_CrearPuesto_DatoEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar_DatoEmpleado;
    private javax.swing.JButton btn_CrearPuesto_DatoEmpleado;
    private javax.swing.JButton btn_Registrar_DatoEmpleado;
    private javax.swing.JComboBox<String> cbx_PuestoTrabajo_DatoEmpleado;
    private javax.swing.JComboBox<String> cbx_Sexo_DatoEmpleado;
    private javax.swing.JCheckBox ck_Activo_DatoEmpleado;
    private javax.swing.JCheckBox ck_Inactivo_DatoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_Apellido_DatoEmpleado;
    private javax.swing.JTextField txt_DNI_DatoEmpleado;
    private javax.swing.JTextField txt_Nombre_DatoEmpleado;
    private javax.swing.JTextField txt_NumeroContacto_DatoEmpleado;
    // End of variables declaration//GEN-END:variables
}
